version: "3.9"

services:
  database:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=<replace_me_with_password>
    ports:
      - 5432:5432
    volumes:
      - ./.db/data:/var/lib/postgresql/data
